# .github/workflows/main.yml
name: Test Proxies

on:
  workflow_dispatch:

jobs:
  test-proxies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Download and install Sing-box
        run: |
          SINGBOX_VERSION="1.11.15"
          wget https://github.com/SagerNet/sing-box/releases/download/v${SINGBOX_VERSION}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          tar -xzf sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz
          sudo mv sing-box-${SINGBOX_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box
          sudo chmod +x /usr/local/bin/sing-box
          sing-box version

      - name: Install speedtest-cli
        run: sudo apt-get install -y speedtest-cli

      - name: Run proxy tester
        run: node index.js

      - name: Commit results
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          JSON_FILE="tested${TIMESTAMP}.json"
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add "$JSON_FILE"
          if ! git diff --staged --quiet; then
            git commit -m "Update proxy test results ($TIMESTAMP)"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
          else
            echo "No changes to proxy results."
          fi
